grafana:

  enabled: true

  adminPassword: admin123

  service:
      type: NodePort
      nodePort: 32500

prometheus:

  prometheusSpec:

    retention: 15d

    storageSpec:

      volumeClaimTemplate:

        spec:

          accessModes:

            - ReadWriteOnce

          resources:

            requests:

              storage: 3Gi

  service:
      type: NodePort
      nodePort: 31249

alertmanager:

  enabled: false
