apiVersion: v1
kind: Service

metadata:
  name: flask-api
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: flask-api

  ports:
    - protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}

  type: ClusterIP
